openapi: 3.0.1
info:
  title: APIInterfazPazYSalvos
  description: API Definition of APIInterfazPazYSalvos
  version: 1.0.0
servers:
- url: http://localhost:8290/apihubintpazsalvos
paths:
  /readvalidateinterfacestudents:
    get:
      parameters:
      - name: studentid
        in: query
        schema:
          type: string
      responses:
        default:
          description: Default response
