openapi: 3.0.1
info:
  title: ApiHubURosario
  description: API Definition of ApiHubURosario
  version: 1.0.0
servers:
- url: http://localhost:8290/apihubiurosario
paths:
  /readvalidatebduxxi:
    get:
      parameters:
      - name: studentid
        in: query
        schema:
          type: string
      responses:
        default:
          description: Default response
  /readvalidatewssap:
    get:
      parameters:
      - name: studentid
        in: query
        schema:
          type: string
      responses:
        default:
          description: Default response
  /readvalidatewskoha:
    get:
      parameters:
      - name: studentid
        in: query
        schema:
          type: string
      responses:
        default:
          description: Default response
